.gitignore, .travis.yml, Dockerfile, Makefile, apis/metacontroller/v1alpha1/register.go, apis/metacontroller/v1alpha1/types_workflow.go, controller/composite/controller_revision.go, go.sum, manifests/dev/args.yaml, manifests/dev/image.yaml, manifests/metacontroller-namespace.yaml, manifests/metacontroller-rbac.yaml, manifests/metacontroller.yaml, test/integration/composite/composite_test.go, test/integration/decorator/decorator_test.go, test/integration/framework/crd.go, test/integration/framework/fixture.go, test/integration/framework/main.go, test/integration/framework/metacontroller.go, third_party/kubernetes/pointer.go
This commit tries to add comments necessary to bring up a new contributor to speed w.r.t integration tests. Among other things it has following changes as well:
- Changes to metac instead of metacontroller wherever appropriate
- fixes to API schema
- fixes to integration test code
=> add required comments to integration codebase

.travis.yml
=> add travis comments that explains its jobs

README.md
=> update the README with how to pronounce metac

.travis.yml
=> add cache to travis that should reduce the travis build time

go.sum
=> add vendoring changes

controller/common/common.go, controller/common/manage_children.go, controller/common/manager.go, controller/decorator/controller.go, controller/decorator/selector.go, dynamic/apply/apply.go, dynamic/lister/lister.go
This commit has following changes:
- adds comments to make the code readable
- new file that manages child resources
=> refactor management of child resources

controller/composite/controller.go, controller/composite/controller_revision.go, controller/composite/metacontroller.go, controller/composite/rolling_update.go, dynamic/clientset/clientset.go, dynamic/controllerref/controller_revision.go, dynamic/controllerref/unstructured.go, third_party/kubernetes/controller.go, third_party/kubernetes/controller_ref_manager.go
This commit has below changes:
- rename variables/functions to make them more readable
- add comments wherever appropriate to let contributors/readers understand metac project
=> refactor composite controller to add code level comments

README.md, TODO, dynamic/clientset/clientset.go, hack/get-kube-binaries.sh, manifests/metacontroller.yaml, test/integration/composite/composite_test.go, test/integration/decorator/decorator_test.go, test/integration/framework/apiserver.go, test/integration/framework/crd.go, test/integration/framework/etcd.go, test/integration/framework/fixture.go, test/integration/framework/helper.go, test/integration/framework/main.go, test/integration/framework/metacontroller.go, test/integration/framework/webhook.go
This commit has following changes:
- renames few functions to make them more understood
- add logs to enable easy debug of integration tests
=> refactor integration tests

apis/metacontroller/v1alpha1/types_generic.go, controller/common/manage_attachments.go, controller/generic/controller.go, controller/generic/hooks.go, main.go
This commit has other changes like more code level comments to make it easier to understand and contribute.
=> fix json property in genericcontroller spec

README.md, TODO, apis/metacontroller/v1alpha1/types_generic.go
=> update readme & todo to reflect priority works

Makefile, README.md, TODO, controller/common/common.go, controller/common/manage_attachments.go, controller/generic/controller.go, controller/generic/metacontroller.go, docs/_guide/troubleshooting.md, examples/service-per-pod/README.md, examples/service-per-pod/service-per-pod.yaml, examples/service-per-pod/test.sh, kustomization.yaml, manifests/metacontroller.yaml, test/integration/framework/fixture.go, test/integration/framework/metacontroller.go, test/integration/generic/generic_test.go
This commit makes the integration test run successfully for GenericController. It has certain log message changes as well.
=> fix generic controller reconcile logic

TODO, examples/service-per-pod/test.sh, examples/status/README.md, examples/status/my-noop.yaml, examples/status/operator.yaml, examples/status/sync.js, examples/status/test.sh
=> refactor examples/status to conform to Metac

examples/bluegreen/README.md, examples/bluegreen/operator.yaml, examples/bluegreen/test.sh, examples/status/test.sh
=> refactor bluegreen example to work using Metac

controller/composite/controller.go, controller/composite/metacontroller.go, controller/decorator/controller.go, controller/decorator/metacontroller.go, controller/generic/controller.go, controller/generic/metacontroller.go, main.go, server/server.go, test/integration/framework/main.go
As per https://kubernetes.slack.com/archives/CA0SUPUDP/p1569866638024700
=> Make number of workers configurable

config/config.go
=> [local] fix config to avoid directories

examples/gctl/set-status-on-cr/go.mod, examples/gctl/set-status-on-cr/go.sum
=> [example] update set-status-on-cr to latest metac commit

examples/gctl/set-status-on-cr/README.md
=> [example] improved README for set-status-on-cr example

controller/generic/metacontroller.go
This commit adds wait logic that allows all declared configurations to load and start respective watch controllers. This wait logic introduces interval and timeout to accomplish this task versus earlier
method of continuous looping that might result in starving other threads to perform their tasks. For example, if one or more configs met with persisting issues earlier logic would have retried forever compared to current polling logic which will error out when retry timeout elapses.
=> [config] add wait for all metac configs to load

examples/gctl/uninstall-openebs/README.md, examples/gctl/uninstall-openebs/go.mod, examples/gctl/uninstall-openebs/go.sum, examples/gctl/uninstall-openebs/openebs_ns.yaml, examples/gctl/uninstall-openebs/openebs_sa_and_crds.yaml, examples/gctl/uninstall-openebs/operator.yaml, examples/gctl/uninstall-openebs/test.sh
This commit updates this example to use the latest version of metac library. It has updated yamls, README and test.sh files.
=> [example] add updated metac to clean uninstall openebs

examples/gctl/set-status-on-cr/go.sum, examples/gctl/uninstall-openebs/go.mod, examples/gctl/uninstall-openebs/go.sum
=> [example] update uninstall-openebs to latest metac

examples/gctl/uninstall-openebs/test.sh
This commit updates test.sh that automates verification of uninstalling openebs
=> [example] update steps to automate uninstall openebs

README.md
closes https://github.com/AmitKumarDas/metac/issues/66
=> chore(readme): update readme with latest info

controller/common/manage_attachments.go
=> Move delete logs

examples/go/my-thing.yaml, examples/go/thing-controller.yaml
- Corrected the thing-controller Example placed /examples/go/
Signed-off-by: Rahul M Chheda <rahul.chheda@mayadata.io>
=> fix(examples): fix thing-controller example

controller/common/manage_children.go, dynamic/apply/apply.go, dynamic/apply/apply_test.go
This commit adds several unit tests w.r.t server side apply of lists and list of maps. In addition, there are additions and changes to code level comments to let Metacontroller's server side apply logic be easy to understand. Finally, there are few changes to logging during server side apply execution.
=> chore(apply): add unit tests and logging w.r.t server side apply

.github/semantic.yml
https://github.com/zeke/semantic-pull-requests
=> chore: #64 - Add initial semantic-pull-request configuration

Dockerfile.debug, Makefile
- Rebase to a distroless base image
- Add a debug image
Fixes  https://github.com/AmitKumarDas/metac/issues/106
=> improvement: use a distroless baseimage

examples/nodejs/Dockerfile, examples/nodejs/Makefile, examples/nodejs/server.js
Update nodejs service used in example to LTS release / run unprivileged
Signed-off-by: Florian Koch <flo@ctrl.wtf>
=> chore(examples): update nodejs to LTS release / run unprivileged

dynamic/apply/apply.go
https://github.com/AmitKumarDas/metac/issues/82 
change loglevel to V5
Signed-off-by: Florian Koch <flo@ctrl.wtf>
=> chore(loglevel): #82 change loglevel to V5

Makefile, apis/metacontroller/v1alpha1/selector.go, controller/common/controller.go, controller/common/controller_test.go, controller/common/manage_children.go, controller/composite/controller.go, controller/composite/controller_revision.go, controller/composite/metacontroller.go, controller/composite/rolling_update.go, controller/decorator/controller.go, controller/decorator/metacontroller.go, controller/decorator/selector.go, controller/generic/controller.go, controller/generic/metacontroller.go, controller/generic/selector.go, controller/generic/selector_test.go, controller/generic/updatestrategy.go, dynamic/clientset/clientset.go, dynamic/discovery/discovery.go, dynamic/informer/factory.go, dynamic/informer/informer.go, helm/metac/crds/metac.openebs.io_genericcontrollers.yaml, manifests/metacontroller.yaml, server/server.go, test/integration/framework/crd.go, test/integration/framework/main.go
Several naming and structural changes have been done to make the code simple to maintain
In addition, this PR has changes to include `omitempty` tags to selector schema fields
closes https://github.com/AmitKumarDas/metac/issues/126
closes https://github.com/AmitKumarDas/metac/issues/115
=> chore(refactor): make common & dynamic packages readable
