controller/common/finalizer/finalizer.go, controller/composite/controller.go, controller/decorator/controller.go, controller/decorator/hooks.go, controller/decorator/metacontroller.go, controller/decorator/selector.go, dynamic/clientset/clientset.go, dynamic/informer/factory.go, dynamic/informer/informer.go
This commit adds code level comments, renames a few variables as part of deeper understanding of decorator controller. This has been done to reduce the steep learning curve required by contributors to understand and use this controller/library.
This is part of a series of commits that will lead to implementing unit tests as well re-packaging dynamic package to enable using the same as a library in other projects.
=> refactor decorator controller as part of further understanding

docs/_guide/troubleshooting.md, examples/service-per-pod/README.md, examples/service-per-pod/my-statefulset.yaml, examples/service-per-pod/operator.yaml, examples/service-per-pod/test.sh
This is the first of changes w.r.t examples folder that makes use of metac. There will be similar changes that needs to be done to rest of the examples to comply with metac.
=> change the examples/service-per-pod to work with metac

Makefile, TODO, apis/metacontroller/v1alpha1/types_generic.go, apis/metacontroller/v1alpha1/zz_generated.deepcopy.go, controller/common/common.go, controller/common/hooks.go, controller/common/manage_attachments.go, controller/common/manage_children.go, controller/generic/controller.go, controller/generic/options.go, controller/generic/updatestrategy.go, docs/_guide/troubleshooting.md, dynamic/apply/apply.go, dynamic/discovery/discovery.go, go.mod, go.sum, test/integration/framework/crd.go, test/integration/framework/fixture.go, test/integration/framework/helper.go, test/integration/framework/metacontroller.go, test/integration/generic/generic_test.go, test/integration/generic/ns_crd_uninstall_test.go, third_party/kubernetes/pointer.go
This commit has fixes and enhancements that were required to implement clean un-install use case. This use case talks about deletion of CRDs and custom resources belonging to a particular workload when that workload's namespace is deleted. This use case takes care of cases where these custom resources might have finalizers set against them.
While this works, there is certainly more amount of work that needs to get into Metac.
Among other things Metac's GenericController needs to be improved further to default to 2-way merge or 3-way merge (kubectl like apply) depending on scenarios. In this particular case, 2-way merge seemed to be a good choice over 3-way merge. Since, Metac does not support 2-way merge, this example had to make use of sync as well as finalize hook to achieve the end …
=> add integration test for clean un-install use case

Dockerfile, TODO, config/config.go, config/config_test.go, controller/generic/controller.go, controller/generic/metacontroller.go, controller/generic/selector.go, go.mod, main.go, server/server.go, test/integration/framework/main.go, third_party/kubernetes/pointer.go, third_party/kubernetes/yaml.go, third_party/kubernetes/yaml_test.go
This commit is first of the series of commits that will enable metac to be run from **_local config_** in addition to the current way of running it by watching Kubernetes based custom resources i.e.
via _CompositeController_, _DecoratorController_ & _GenericController_ resource kinds.
This commit focuses on enabling running metac from local config for generic controller only. Once this feature graduates from experimental to stable, it will be added to other meta controllers.
Some of the typical usecases that are fit for this local mode of running metac include: _Install_, _Un-Install_, _Upgrade_, _Conformance Tests_, etc. One would typically like to avoid depending on additional CRDs to get these requirements done. In such cases, one hopes to deploy a container that makes use of metac …
=> [local] add option to run metac from local config

TODO, controller/generic/controller.go, controller/generic/hooks.go
SkipReconcile is a flag that skips reconciliation of GenericController's attachments. This tunable is only supported for GenericController.
SkipReconcile looks similar to GenericController's spec.ReadOnly. However, both of them serve different purposes. SkipReconcile is dynamic and is set by the sync hook implementation. However ReadOnly is a static option that is set in GenericController's spec.
In other words, one expects SkipReconcile to vary from true to false or vice versa depending on runtime conditions. On the other hand, ReadOnly is expected to be set to true or false for the entire
lifecycle of the controller.
=> add skipReconcile to GenericController hook response

TODO, controller/common/finalizer/finalizer.go, controller/common/manage_attachments.go, controller/common/manage_children.go, controller/composite/controller.go, controller/decorator/controller.go, controller/doc.go, controller/generic/controller.go, controller/generic/selector.go, controller/generic/updatestrategy.go, dynamic/apply/apply_test.go, dynamic/object/metadata.go, test/integration/framework/crd.go, test/integration/framework/fixture.go, test/integration/framework/main.go, test/integration/generic/install_uninstall_crd_test.go, test/integration/generic/stuck_to_unstuck_delete_test.go
This commit has following changes:
- Implement separate selectors for watch & attachments. This helps in having a resource kind be available in watch as well as attachment but differ by their selector rule.
- Fixes the error when gctl has only Finalize hook set
- Adds new unit tests w.r.t apply logic
- Adds new integration tests w.r.t stuck namespace deletion
- This commit has better log messages, improved code level comments
=> separate selector logic for watch & attachments of gctl

config/config.go, examples/gctl/set-status-on-cr/Dockerfile, examples/gctl/set-status-on-cr/README.md, examples/gctl/set-status-on-cr/config.yaml, examples/gctl/set-status-on-cr/operator.yaml
This commit adds some logs/debug information while loading the local configs used to start and run generic meta controller.
In addition, this has few changes to examples that make use of inline hook, local config & generic controller.
=> [local] add logs to local config based metac run

Makefile, apis/metacontroller/v1alpha1/types_generic.go, controller/generic/controller.go, controller/generic/metacontroller.go, examples/gctl/set-status-on-cr/main.go, server/server.go, start/start.go, test/integration/composite/composite_test.go, test/integration/decorator/decorator_test.go, test/integration/framework/crd.go, test/integration/framework/main.go, test/integration/framework/metacontroller.go, test/integration/generic/set_status_on_cr_test.go, test/integration/genericlocal/set_status_on_cr_test.go, test/integration/genericlocal/suite_test.go
This commit found various issues w.r.t running metac in local mode. Local mode implies running metac using metacontroller as a config file versus using the same as a kubernetes CRD. These issues were
caught as a result of writing integration tests. Integration tests itself had to be enhanced to support this mode of metac.
=> [fix] running metac from config

examples/gctl/set-status-on-cr/README.md, examples/gctl/set-status-on-cr/coolnerd.yaml, examples/gctl/set-status-on-cr/ns_and_crd.yaml, examples/gctl/set-status-on-cr/operator.yaml, examples/gctl/set-status-on-cr/rbac.yaml, examples/gctl/set-status-on-cr/test.sh
This commit showcases an example of a standalone binary that has the
following:
- uses metac as a library,
- uses GenericController as a config to run this binary &
- makes use of inline hook that implements the reconcile logic
Here reconcile logic is what the name of the folder suggests. In other words, the reconcile logic sets a custom resource's status.
=> [example] update set-status-on-cr example with README.md & test.sh

config/config.go, config/config_test.go, config/testdata/test_cctl.yaml, config/testdata/test_dctl.yaml, config/testdata/test_gctl.yaml, examples/gctl/uninstall-openebs/openebs_crs.yaml, examples/gctl/uninstall-openebs/test.sh
This commit limits loading of metac config files with either .json or .yaml extension.
In addition, there is new unit test & some golden files to cover the same.
=> [config] fix loading of metac config file(s)

README.md, controller/common/common.go, controller/generic/controller.go
This commit fixes the name of the finalizer to avoid namespace if the watch is not namespaced. This finalizer is set against watch resource declared in GenericController if there is a finalizer hook in the specs of GenericController.
=> [fix] name of finalizer assigned to watch resource

examples/gctl/uninstall-openebs/go.mod, examples/gctl/uninstall-openebs/go.sum, examples/gctl/uninstall-openebs/openebs_crs.yaml, examples/gctl/uninstall-openebs/operator_rbac.yaml
This commit updates the rbac rules required to run uninstall openebs example. In addition, it updates to use the latest version of metac. It is important to make use of this latest metac since that includes a bug fix.
=> [example] update rbac for uninstall-openebs example

examples/gctl/uninstall-openebs/config/config.yaml, examples/gctl/uninstall-openebs/main.go, examples/gctl/uninstall-openebs/operator_rbac.yaml
This commit fixes the logic w.r.t uninstall openebs example. It sets hook response's Finalized state to true if there are no attachments in the hook request. This in turn removes metac's finalizer from namespace and lets this namespace to get deleted.
=> [example] fix example on uninstall openebs

controller/common/manage_attachments.go, controller/generic/controller.go
This commit adds a new option that allows metac to update a resource even if this resource is pending deletion. This option is currently only supported in GenericController during finalize hook invocation.
=> [gctl] add UpdateDuringPendingDelete option

examples/gctl/uninstall-openebs/config/config.yaml, examples/gctl/uninstall-openebs/go.mod, examples/gctl/uninstall-openebs/go.sum
This commit updates uninstall openebs code to point to latest metac. In addition, it updates the GenericController config to use appropriate update strategy.
=> [example] update uninstall openebs example to latest metac

Dockerfile
Resolve #72 
- Updated version of Go to 1.13.5 in Dockerfile
- Add Pre-test image to the Dockerfile to make sure it's working with 1.13.5
=> Update Go in Dockerfile

examples/sample-controller/js/README.md, examples/sample-controller/js/foo.yaml, examples/sample-controller/js/operator.yaml, examples/sample-controller/js/sync.js, examples/sample-controller/js/test.sh
This commit adds a new example that compares the Metacontroller way of writing controllers versus the one present at: https://github.com/kubernetes/sample-controller
This is the javascript version of sample controller. We might include `python` & `go` versions in near future.
=> examples(sample-controller): add javascript based sample controller

hack/get-kube-binaries.sh
This commit updates integration test dependencies to use kubernetes 1.16.4 and etcd 3.4.2
=> chore(integration-test): bump kubernetes & etcd versions

examples/sample-controller/js/README.md, go.mod
This commit has the change due to the automatic go dependency update. In addition, a typo from examples has been fixed.
=> chore(go module): update go dependencies

.github/workflows/test-release.yaml, hack/get-kube-binaries.sh, release.config.js
Configuration based on recipe  for https://github.com/marketplace/actions/action-for-semantic-release
Currently set to :
* branches - master and semantic-release (for testing)
Job output https://github.com/grzesuav/metac/actions/runs/57755684
* click on `Release` on the left
* you can expand to see `Release` in logs
I have triggered a release on my fork : 
https://github.com/grzesuav/metac/releases
=> chore(semantic-release): #64 - Enable semantic release

examples/sample-controller/js/foo.yaml, examples/sample-controller/js/operator.yaml, examples/sample-controller/js/test.sh
fixes https://github.com/AmitKumarDas/metac/issues/127
In newer kubernetes version, the namespace k8s.io is protected
https://github.com/kubernetes/enhancements/pull/1111
switch sample controller to use example.io instead
Signed-off-by: Florian Koch <flo@ctrl.wtf>
=> fix(examples): replace k8s.io with example.io

examples/cctl/hello-python/controller.yaml, examples/cctl/hello-python/crd.yaml, examples/cctl/hello-python/readme.md, examples/cctl/hello-python/sync.py, examples/cctl/hello-python/webhook.yaml
If you are using _'CompositeController'_ one basic misconfiguration can lead the controller to continuous reconciliations. When _'CompositeController'_ is used with the parent resource's status **undefined** as a sub-resource, then the reconciliation gets into an infinite loop. This happens since _'CompositeController'_ updates _'status.observedGeneration'_ with _'metadata.generation'_ as part of its reconciliation.
Following sums up the reconciliation logic when status is defined as a sub resource & vice-versa:
1. If parent's status is defined as a sub resource then reconciliation logic patches this status using status api end point. This does not change resource's `metadata.generation` field.
2. If parent's status is not defined as a sub resource then reconciliation logic updates the …
=> chore(examples): add hello-python example using CompositeController

.github/workflows/test-release.yaml, dynamic/discovery/discovery.go
This PR does the following changes
- Adds functionality to discover the list of resources based
on their kind. This functionality will help consumers to get
resource details if they are aware of Resource Kind.
- Updates the way of configuring GitHub WorkFlow
Path and Envs(For more info click [here](https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/)).
Signed-off-by: mittachaitu <sai.chaithanya@mayadata.io>
=> feat(discovery): add method to list resources based on kind
